# Generated by Django 5.2.4 on 2025-10-14 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_department_alter_teacher_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
    ]
