# Generated by Django 5.2.4 on 2025-10-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_teacher_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='hod',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
