# Generated by Django 5.2.4 on 2025-10-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_remove_student_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
