# Generated by Django 5.2.4 on 2025-10-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_alter_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='school.subject'),
        ),
    ]
