# Generated by Django 5.2.4 on 2025-10-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_teacher_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='credits',
        ),
    ]
