# Generated by Django 5.2.4 on 2025-10-28 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_remove_subject_credits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='subject',
            new_name='subjects',
        ),
    ]
