# Generated by Django 5.2.4 on 2025-10-29 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_rename_subject_teacher_subjects'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('student', 'date')},
        ),
        migrations.RemoveField(
            model_name='teacherattendance',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='teacherattendance',
            name='check_out',
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('on_leave', 'On Leave'), ('half_day', 'Half Day')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('on_leave', 'On Leave'), ('half_day', 'Half Day')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='subject',
        ),
    ]
