# Generated by Django 5.2.4 on 2025-11-03 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_alter_studentattendance_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
