# Generated by Django 5.2.4 on 2025-11-03 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_delete_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=10)),
                ('period', models.CharField(choices=[('1', 'Period 1 (09:00 - 09:45)'), ('2', 'Period 2 (09:45 - 10:30)'), ('3', 'Period 3 (10:45 - 11:30)'), ('4', 'Period 4 (11:30 - 12:15)'), ('5', 'Period 5 (12:15 - 13:00)'), ('6', 'Period 6 (13:45 - 14:30)'), ('7', 'Period 7 (14:30 - 15:15)')], max_length=10)),
                ('room_number', models.CharField(blank=True, max_length=20, null=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='school.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teacher')),
            ],
            options={
                'ordering': ['day', 'period'],
                'unique_together': {('class_obj', 'day', 'period'), ('room_number', 'day', 'period'), ('teacher', 'day', 'period')},
            },
        ),
    ]
