# Generated by Django 5.2.4 on 2025-11-06 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_timetable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('class_obj', 'day', 'period'), ('teacher', 'day', 'period')},
        ),
    ]
