# Generated by Django 5.2.4 on 2025-11-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_alter_timetable_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='period',
            field=models.IntegerField(choices=[('1', 'Period 1 (09:00 - 09:45)'), ('2', 'Period 2 (09:45 - 10:30)'), ('3', 'Period 3 (10:45 - 11:30)'), ('4', 'Period 4 (11:30 - 12:15)'), ('5', 'Period 5 (12:15 - 13:00)'), ('6', 'Period 6 (13:45 - 14:30)'), ('7', 'Period 7 (14:30 - 15:15)')]),
        ),
    ]
