# Generated by Django 5.2.4 on 2025-11-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0028_account'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_type', 'teacher_salary')), fields=('teacher', 'month'), name='unique_teacher_monthly_salary'),
        ),
    ]
