# Generated by Django 5.2.4 on 2025-11-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0029_account_unique_teacher_monthly_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='yearly_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
