# Generated by Django 5.2.4 on 2025-11-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0030_class_yearly_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='expense_category',
            field=models.CharField(blank=True, choices=[('academic', 'Academic expense'), ('administration', 'Administration Expense'), ('infrastructure', 'Infrastructure Expense'), ('other', 'Other expense')], max_length=100, null=True),
        ),
    ]
